const mongoose = require('mongoose');

const memberSchema2 = new mongoose.Schema({
  Timestamp: String,
  FormId: String,
  BusinessName: String,
  YearOfEstablishment: String,
  BusinessCategory: String,
  ListOfServicesOffered: String,
  BusinessRegistrationNumber: String,
  BusinessPhoneNumber: String,
  BusinessEmailAddress: String,
  BusinessWebsite: String,
  AnyOneSocialMediaProfileOptional: String,
  GenderIdentity: String,
  BusinessAddress: String,
  BusinessState: String,
  BusinessDistrict: String,
  AboutYourBusiness: String,
  WhatSetsYouApartFromCompetitors: String,
  ServiceLocation1Country: String,
  ServiceLocation1State: String,
  ServiceLocation1District: String,
  ServiceLocation2Country: String,
  ServiceLocation2State: String,
  ServiceLocation2District: String,
  ServiceLocation3Country: String,
  ServiceLocation3State: String,
  ServiceLocation3District: String,
  ServiceLocation4Country: String,
  ServiceLocation4State: String,
  ServiceLocation4District: String,
  ServiceLocation5Country: String,
  ServiceLocation5State: String,
  ServiceLocation5District: String,
  ServiceLocation6Country: String,
  ServiceLocation6State: String,
  ServiceLocation6District: String,
  ServiceLocation7Country: String,
  ServiceLocation7State: String,
  ServiceLocation7District: String,
  ServiceLocation8Country: String,
  ServiceLocation8State: String,
  ServiceLocation8District: String,
  ServiceLocation9Country: String,
  ServiceLocation9State: String,
  ServiceLocation9District: String,
  ServiceLocation10Country: String,
  ServiceLocation10State: String,
  ServiceLocation10District: String,
  AnnualTurnoverIn: String,
  personphoto: String,
  relphoto: String,
  pdf: String,
  WhatDoYouExpectFromRIFAH: String,
  PasswordForLogin: String,
  Salt: String
});


module.exports = mongoose.model('Member2', memberSchema2);  
